### ISSUE TITLE
Unable to calibrate the probe

### ISSUE THREAD

**Issue by Bighoneypot** [GreenPonik/DFRobot_ESP_PH_WITH_ADC_BY_GREENPONIK#3]
I am testing your firmware, but it is impossible to calibrate.
When I insert the probe in the solution of ph 4.0 I have this error >>> Buffer Solution Error Try Again <<<
Devices used:

1 ads1115
1 esp32
1 dfrobot phmeter (https://www.dfrobot.com/product-1668.html)

Do you have an idea about the problem?

![image](https://user-images.githubusercontent.com/35570068/112648835-33a35b80-8e4a-11eb-9225-063d895780b6.png)

**Comment by MkLHX** [comment]
Hi @Bighoneypot 
As it wrote on main page the lib only works with 
using Gravity: Analog pH Sensor / Meter Kit V2, SKU:SEN0161-V2 + ADC ADS1115

Due to the voltage range of your pH sensor i can say the problem i the voltage range of the signal returned by the circuit.

You can see voltage is around 300 and pH 13.37 so if you want calibrate for pH 4.0 that can't work.

here you can find the voltage corresponding to pH value.
https://github.com/GreenPonik/DFRobot_ESP_PH_WITH_ADC_BY_GREENPONIK/blob/master/src/DFRobot_ESP_PH_WITH_ADC.h#L39

This is a linear signal you can change voltage for pH 4.0 and voltage for pH 7.0 in the header and test if that work.

I can't help you because i haven't this sensor and circuit.

**Comment by Bighoneypot** [comment]
Thank you @MkLHX  for your answer.
Now I have this :

Ph have a good calibration for 4.0
![image](https://user-images.githubusercontent.com/35570068/112827285-6a69b380-908e-11eb-8a1c-b7c31e1ff4a3.png)

but I put probe into a pH 7.0 I have this result : 
![image](https://user-images.githubusercontent.com/35570068/112827395-938a4400-908e-11eb-8bdf-cf23186e3645.png)


do you have Idea for this issue?

Thank you!!!

**Comment by MkLHX** [comment]
Hi @Bighoneypot 

Same answer, voltage range isn't the good. For pH 7.0 the voltage have to be around 1134mv
https://github.com/GreenPonik/DFRobot_ESP_PH_WITH_ADC_BY_GREENPONIK/blob/master/src/DFRobot_ESP_PH_WITH_ADC.h#L41

Your current value is aroudn 1570mv and this is the voltage for pH under 4.0
https://github.com/GreenPonik/DFRobot_ESP_PH_WITH_ADC_BY_GREENPONIK/blob/master/src/DFRobot_ESP_PH_WITH_ADC.h#L44

You have to understand the pH / voltage couple is linear invert signal

e.g.(that not the real graph for DFRobot circuit)
![image](https://user-images.githubusercontent.com/17542841/112830492-e239dd00-9092-11eb-9512-6e52f001653a.png)
(find with duckduckgo: https://www.66pacific.com/ph/images/ph_cal_chart.gif)

So you cannot use our library without same electrical (pH probe and circuit) and chemical (solutions) conditions.

**Comment by Bighoneypot** [comment]
Hi @MkLHX , to use your libraries I need to buy this ??
https://www.amazon.it/Gravit%C3%A0-Sensore-analogico-kit-misuratore/dp/B07L2RSHYN/ref=sr_1_5?__mk_it_IT=%C3%85M%C3%85%C5%BD%C3%95%C3%91&dchild=1&keywords=dfrobot+ph&qid=1617031188&sr=8-5

**Comment by MkLHX** [comment]
You need the same reference that describe on the home page
